#' @title Visualize branching structure of multi-path forward selection
#'
#' @description This function produces a graph visualization of the branching
#' structure
#' generated by \code{build_paths()}. Each model is a node, and edges connect
#' parent → child models. Nodes are arranged by their forward-selection step,
#' making the multi-path search tree easy to inspect.
#'
#' @param forest A \code{path_forest} object returned by \code{build_paths()}.
#' @param vertex_size Numeric; vertex size for plotting (default = 22).
#' @param vertex_color Character; node color (default = "skyblue").
#' @param edge_color Character; edge color (default = "gray40").
#' @param label_cex Numeric; text size for node labels (default = 0.6).
#' @param layout Logical; if TRUE (default), use a layered layout by step.
#'
#' @return Invisibly returns the igraph object used for plotting.
#'
#' @export
plot_branching <- function(forest,
                           vertex_size = 22,
                           vertex_color = "skyblue",
                           edge_color = "gray40",
                           label_cex = 0.6,
                           layout = TRUE) {

  ## ---- Basic checks ----
  if (is.null(forest$frontiers)) {
    stop("forest must be a path_forest object with a $frontiers component.")
  }

  # Collect all parent → child edges
  edges <- do.call(rbind, lapply(forest$frontiers[-1], function(df) {
    data.frame(parent = df$parent, child = df$key, stringsAsFactors = FALSE)
  }))

  # Combine all nodes
  all_nodes <- unique(c(edges$parent, edges$child))
  all_nodes <- all_nodes[!is.na(all_nodes)]

  # Build igraph object
  g <- igraph::graph_from_data_frame(edges, directed = TRUE, vertices = all_nodes)

  ## ---- Determine step of each node ----
  # We locate each model's step using the combined aic_by_model table
  step_lookup <- forest$aic_by_model$step
  names(step_lookup) <- forest$aic_by_model$key

  node_steps <- step_lookup[igraph::V(g)$name]
  node_steps[is.na(node_steps)] <- 0  # empty model (root)

  ## ---- Layout: arrange nodes by step ----
  if (layout) {
    # x = step, y = within-step rank
    step_order <- split(igraph::V(g)$name, node_steps)
    coords <- do.call(rbind, lapply(names(step_order), function(s) {
      v <- step_order[[s]]
      cbind(
        x = as.numeric(s),                    # horizontal position = step
        y = seq_along(v)                      # vertical spacing
      )
    }))
    rownames(coords) <- unlist(step_order)
    coords <- coords[igraph::V(g)$name, ]     # reorder to match igraph nodes
  } else {
    coords <- NULL  # igraph will pick its own layout
  }

  ## ---- Plot ----
  plot(
    g,
    layout = coords,
    vertex.size = vertex_size,
    vertex.label = igraph::V(g)$name,
    vertex.color = vertex_color,
    vertex.label.cex = label_cex,
    edge.color = edge_color,
    main = "Branching Structure of Multi-Path Forward Selection",
    asp = 0
  )

  invisible(g)
}
